A1.Yes, there is a difference in the data type of variables list_ and array_list as the variable list_ belongs to the datatype 'list' and the variable array_list belongs to the dtype('<U1') unicode whose data size or element bit size is less than 1.

In [1]:
#Example of A1.
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)
type(list_), array_list.dtype

(list, dtype('<U1'))

In [2]:
#A2.
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)
print("The data type of the elements present in the list_ variable : ")
for i in list_:
    print(type(list_), type(i))
print("*******************************************************************")
print("The data type of the elements present in the array_list variable : ")
for i in np.nditer(array_list):
    print(type(i), array_list.dtype)

The data type of the elements present in the list_ variable : 
<class 'list'> <class 'str'>
<class 'list'> <class 'str'>
<class 'list'> <class 'str'>
<class 'list'> <class 'str'>
<class 'list'> <class 'str'>
*******************************************************************
The data type of the elements present in the array_list variable : 
<class 'numpy.ndarray'> <U1
<class 'numpy.ndarray'> <U1
<class 'numpy.ndarray'> <U1
<class 'numpy.ndarray'> <U1
<class 'numpy.ndarray'> <U1


A3. Yes, there will be only one difference that the data type of the elements present in the array_list will be changed into 'int64' from the '<U1' whereas the data type of the elements present in the list_ variable will stay same as 'str'.

In [3]:
#Example of A3.
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_, dtype = int)
print("The updated data type of the elements present in the list_ variable : ")
for i in list_:
    print(type(i))
print("**********************************************************")
print("The updated data type of the elements present in the array_list variable : ")
for i in np.nditer(array_list):
    print(array_list.dtype)

The updated data type of the elements present in the list_ variable : 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
**********************************************************
The updated data type of the elements present in the array_list variable : 
int64
int64
int64
int64
int64


In [4]:
#A4.
import numpy as np
num_list = [[ 1, 2, 3] ,[4, 5, 6]]
num_array = np.array(object = num_list)
#A4. (i)
print("The shape of the array is :", num_array.shape)
#A4. (ii)
print("The size of the array is :", num_array.size)

The shape of the array is : (2, 3)
The size of the array is : 6


In [5]:
#A5.
import numpy.matlib as nm
arr1 = nm.zeros((3,3))
print("The numpy array of 3*3 matrix containing zeros only is given as :")
print(arr1)
#verifying the hint
print(arr1.size)
print(arr1.shape)

The numpy array of 3*3 matrix containing zeros only is given as :
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
9
(3, 3)


In [6]:
#A6.
import numpy.matlib as nm
arr2 = nm.eye(5)
print("The identity matrix of shape (5,5) using numpy functions is given as :")
print(arr2)
#Verifying the hint
print(arr2.shape)

The identity matrix of shape (5,5) using numpy functions is given as :
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
